// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/chat.tsx";
import * as $2 from "./routes/home.tsx";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/login.tsx";
import * as $5 from "./routes/register.tsx";
import * as $$0 from "./islands/chat.tsx";
import * as $$1 from "./islands/header.tsx";
import * as $$2 from "./islands/home_button.tsx";
import * as $$3 from "./islands/title_show.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/chat.tsx": $1,
    "./routes/home.tsx": $2,
    "./routes/index.tsx": $3,
    "./routes/login.tsx": $4,
    "./routes/register.tsx": $5,
  },
  islands: {
    "./islands/chat.tsx": $$0,
    "./islands/header.tsx": $$1,
    "./islands/home_button.tsx": $$2,
    "./islands/title_show.tsx": $$3,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
